sonar

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -37,7 +37,7 @@ jobs:
               -X POST \
               "https://sonarcloud.io/api/projects/create" \
               -d "name=$REPO_NAME" \
-              -d "project=$REPO_NAME" \
+              -d "project=DevSecOp-tarea-final_${REPO_NAME}" \
               -d "organization=devsecop-tarea-final" \
               -d "visibility=public")
             if [ "$create_response" -eq 200 ]; then
@@ -71,4 +71,18 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           REPO_NAME: ${{ github.event.repository.name }}
-        run: ./node_modules/.bin/sonar-scanner -X
+        run: ./node_modules/.bin/sonar-scanner
+
+      - name: Quality Gate Status
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          REPO_NAME: ${{ github.event.repository.name }}
+        run: |
+          status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=DevSecOp-tarea-final_${REPO_NAME}" | jq -r '.projectStatus.status')
+          echo "Quality Gate status: $status"
+          
+          if [ "$status" != "OK" ]; then
+            echo "Quality Gate failed."
+            exit 1
+          fi
+
